### ISSUE TITLE
BUG: Creating a cluster in an existing namespace fails with an exception

### ISSUE THREAD

**Issue by NuckChorris** [sai3010/Typesense-Kubernetes-Operator#1]
**Describe the bug**
When declaring a cluster in an existing namespace, the operator attempts to create/modify the namespace, causing a conflict exception.

**To Reproduce**
1. Create a namespace
2. Set the `spec.namespace` on your `TypesenseOperator` to that namespace
3. Watch the operator fail to create it

**Expected behavior**
Typesense-Kubernetes-Operator handles it gracefully and just skips namespace creation, using the existing namespace.

**Please complete the following information:**
 - Kubernetes version
   - 1.24.16-do.0
 - Typesense version
   - 0.25.0
 - Cloud provider or self-managed?
   - DigitalOcean Managed Kubernetes

**Additional context**
Here are the logs including stack traces:

```
[2023-08-21 05:09:51,948] kopf.objects         [ERROR   ] [kitsu-staging/typesense-cluster] Handler 'create_fn' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/deployment_utils.py", line 53, in create_modify_namespace
    resp = core_obj.create_namespace(body=configuration)
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 6363, in create_namespace
    return self.create_namespace_with_http_info(body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 6454, in create_namespace_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 276, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 235, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'e368d774-b827-4b73-a2c5-f3e01085cfd5', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '4b60295b-b55c-41f9-98ed-5204a86b44cd', 'X-Kubernetes-Pf-Prioritylevel-Uid': '08ca9be3-9053-4572-82ec-d4ef65f21ff8', 'Date': 'Mon, 21 Aug 2023 05:09:51 GMT', 'Content-Length': '216'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"kitsu-staging\" already exists","reason":"AlreadyExists","details":{"name":"kitsu-staging","kind":"namespaces"},"code":409}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/deployment_utils.py", line 57, in create_modify_namespace
    raise Exception(f"Kubernets Api Exception - Namespace: {e.body}")
Exception: Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"kitsu-staging\" already exists","reason":"AlreadyExists","details":{"name":"kitsu-staging","kind":"namespaces"},"code":409}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "handler.py", line 25, in create_fn
    create_modify_namespace(k8s_core_v1,namespace=spec['namespace'])
  File "/deployment_utils.py", line 60, in create_modify_namespace
    raise Exception(f"Exception namespace: {e}")
Exception: Exception namespace: Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"kitsu-staging\" already exists","reason":"AlreadyExists","details":{"name":"kitsu-staging","kind":"namespaces"},"code":409}
[2023-08-21 05:09:51,949] kopf.objects         [DEBUG   ] [kitsu-staging/typesense-cluster] Patching with: {'metadata': {'annotations': {'kopf.zalando.org/create_fn': '{"started":"2023-08-21T05:06:51.321279","delayed":"2023-08-21T05:10:51.948779","purpose":"create","retries":4,"success":false,"failure":false,"message":"Exception namespace: Kubernets Api Exception - Namespace: {\\"kind\\":\\"Status\\",\\"apiVersion\\":\\"v1\\",\\"metadata\\":{},\\"status\\":\\"Failure\\",\\"message\\":\\"namespaces \\\\\\"kitsu-staging\\\\\\" already exists\\",\\"reason\\":\\"AlreadyExists\\",\\"details\\":{\\"name\\":\\"kitsu-staging\\",\\"kind\\":\\"namespaces\\"},\\"code\\":409}\\n"}', 'kopf.zalando.org/touch-dummy': None}}, 'status': {'kopf': {'progress': {'create_fn': {'started': '2023-08-21T05:06:51.321279', 'stopped': None, 'delayed': '2023-08-21T05:10:51.948779', 'purpose': 'create', 'retries': 4, 'success': False, 'failure': False, 'message': 'Exception namespace: Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \\"kitsu-staging\\" already exists","reason":"AlreadyExists","details":{"name":"kitsu-staging","kind":"namespaces"},"code":409}\n', 'subrefs': None}}}}}
[2023-08-21 05:09:51,961] kopf.objects         [WARNING ] [kitsu-staging/typesense-cluster] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'create_fn': {'started': '2023-08-21T05:06:51.321279', 'stopped': None, 'delayed': '2023-08-21T05:10:51.948779', 'purpose': 'create', 'retries': 4, 'success': False, 'failure': False, 'message': 'Exception namespace: Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \\"kitsu-staging\\" already exists","reason":"AlreadyExists","details":{"name":"kitsu-staging","kind":"namespaces"},"code":409}\n', 'subrefs': None}}}}, None),)
[2023-08-21 05:09:51,961] kopf.objects         [DEBUG   ] [kitsu-staging/typesense-cluster] Sleeping was skipped because of the patch, 59.999836 seconds left.
[2023-08-21 05:09:51,969] kopf._core.engines.p [WARNING ] Failed to post an event. Ignoring and continuing. Code: 403. Message: events is forbidden: User "system:serviceaccount:default:typesense-operator-sa" cannot create resource "events" in API group "" in the namespace "kitsu-staging". Details: {'kind': 'events'}Event: type='Error', reason='Logging', message='Handler \'create_fn\' failed with an exception. Will retry.\nTraceback (most recent call last):\n  File "/deployment_utils.py", line 53, in create_modify_namespace\n    resp = core_obj.create_namespace(body=configuration)\n  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 6363, in create_namespace\n    return self.create_namespace_with_http_info(body, **kwargs)  # noqa: E501\n  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 6454, in...ile "handler.py", line 25, in create_fn\n    create_modify_namespace(k8s_core_v1,namespace=spec[\'namespace\'])\n  File "/deployment_utils.py", line 60, in create_modify_namespace\n    raise Exception(f"Exception namespace: {e}")\nException: Exception namespace: Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \\"kitsu-staging\\" already exists","reason":"AlreadyExists","details":{"name":"kitsu-staging","kind":"namespaces"},"code":409}\n'.
[2023-08-21 05:09:52,064] kopf.objects         [DEBUG   ] [kitsu-staging/typesense-cluster] Creation is in progress: {'apiVersion': 'typesenseproject.org/v1', 'config': {'password': 'xyz'}, 'kind': 'TypesenseOperator', 'metadata': {'annotations': {'kopf.zalando.org/create_fn': '{"started":"2023-08-21T05:06:51.321279","delayed":"2023-08-21T05:10:51.948779","purpose":"create","retries":4,"success":false,"failure":false,"message":"Exception namespace: Kubernets Api Exception - Namespace: {\\"kind\\":\\"Status\\",\\"apiVersion\\":\\"v1\\",\\"metadata\\":{},\\"status\\":\\"Failure\\",\\"message\\":\\"namespaces \\\\\\"kitsu-staging\\\\\\" already exists\\",\\"reason\\":\\"AlreadyExists\\",\\"details\\":{\\"name\\":\\"kitsu-staging\\",\\"kind\\":\\"namespaces\\"},\\"code\\":409}\\n"}', 'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"typesenseproject.org/v1","config":{"password":"xyz"},"kind":"TypesenseOperator","metadata":{"annotations":{},"name":"typesense-cluster","namespace":"kitsu-staging"},"spec":{"image":"typesense/typesense:0.25.0","namespace":"kitsu-staging","replicas":3,"resources":{"limits":{"cpu":"2","memory":"512Mi"},"requests":{"cpu":"200m","memory":"512Mi"}},"storageClass":{"name":"do-block-storage","size":"20Gi"}}}\n'}, 'creationTimestamp': '2023-08-21T05:06:51Z', 'finalizers': ['kopf.zalando.org/KopfFinalizerMarker'], 'generation': 1, 'managedFields': [{'apiVersion': 'typesenseproject.org/v1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:config': {'.': {}, 'f:password': {}}, 'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:image': {}, 'f:namespace': {}, 'f:replicas': {}, 'f:resources': {'.': {}, 'f:limits': {'.': {}, 'f:cpu': {}, 'f:memory': {}}, 'f:requests': {'.': {}, 'f:cpu': {}, 'f:memory': {}}}, 'f:storageClass': {'.': {}, 'f:name': {}, 'f:size': {}}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2023-08-21T05:06:51Z'}, {'apiVersion': 'typesenseproject.org/v1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'f:kopf.zalando.org/create_fn': {}}, 'f:finalizers': {'.': {}, 'v:"kopf.zalando.org/KopfFinalizerMarker"': {}}}}, 'manager': 'kopf', 'operation': 'Update', 'time': '2023-08-21T05:09:51Z'}], 'name': 'typesense-cluster', 'namespace': 'kitsu-staging', 'resourceVersion': '283396168', 'uid': '52ac1ca6-2666-4078-9429-ef249f43ada7'}, 'spec': {'image': 'typesense/typesense:0.25.0', 'namespace': 'kitsu-staging', 'replicas': 3, 'resources': {'limits': {'cpu': '2', 'memory': '512Mi'}, 'requests': {'cpu': '200m', 'memory': '512Mi'}}, 'storageClass': {'name': 'do-block-storage', 'size': '20Gi'}}}
[2023-08-21 05:09:52,064] kopf.objects         [DEBUG   ] [kitsu-staging/typesense-cluster] Sleeping for 59.884414 seconds for the delayed handlers.
```

**Comment by sai3010** [comment]
Even though there is an exception raised , it should end up creating your resources. 
Are you not able to update resources in the same namespace?

**Comment by richierichard** [comment]
Hi, I am getting the same issue. The expection has been raised but the resources are not provisioned. Is there a workaround?

**Comment by sai3010** [comment]
> Hi, I am getting the same issue. The expection has been raised but the resources are not provisioned. Is there a workaround?
> 
> ```
> kopf.zalando.org/create_fn: '{"started":"2023-09-06T14:06:56.627706","delayed":"2023-09-06T14:58:06.440484","purpose":"create","retries":51,"success":false,"failure":false,"message":"Exception
>       namespace: Kubernets Api Exception - Namespace: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"namespaces
>       \\\"typesense-server\\\" already exists\",\"reason\":\"AlreadyExists\",\"details\":{\"name\":\"typesense-server\",\"kind\":\"namespaces\"},\"code\":409}\n"}'
> ```
> 
> ```
> [2023-09-06 15:01:07,169] kopf.objects         [ERROR   ] [typesense-server/typesense-server] Handler 'create_fn' failed with an exception. Will retry.
> Traceback (most recent call last):
>   File "/deployment_utils.py", line 53, in create_modify_namespace
>     resp = core_obj.create_namespace(body=configuration)
>   File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 6363, in create_namespace
>     return self.create_namespace_with_http_info(body, **kwargs)  # noqa: E501
>   File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 6454, in create_namespace_with_http_info
>     return self.api_client.call_api(
>   File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
>     return self.__call_api(resource_path, method,
>   File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
>     response_data = self.request(
>   File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 391, in request
>     return self.rest_client.POST(url,
>   File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 276, in POST
>     return self.request("POST", url,
>   File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 235, in request
>     raise ApiException(http_resp=r)
> kubernetes.client.exceptions.ApiException: (409)
> Reason: Conflict
> HTTP response headers: HTTPHeaderDict({'Audit-Id': '7bb697d5-e984-489c-8134-e64aa368fbd0', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'f0c1e1ee-b99d-4198-9fbd-eed822800add', 'X-Kubernetes-Pf-Prioritylevel-Uid': '5d8799a1-1696-4fa9-94ee-4f9e5e51ae38', 'Date': 'Wed, 06 Sep 2023 15:01:07 GMT', 'Content-Length': '222'})
> HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"typesense-server\" already exists","reason":"AlreadyExists","details":{"name":"typesense-server","kind":"namespaces"},"code":409}
> ```

Hi 
Did you do `kubectl apply` or `kubectl create`?

**Comment by richierichard** [comment]
@sai3010 thanks for taking time to reply. I have used `kubectl apply`.

**Comment by sai3010** [comment]
Hi @NuckChorris @richierichard  Please use `kubectl apply` when applying changes. Use `kubectl create` only for the first time when you are creating the typesense cluster.

Please refer to the document, the same thing is mentioned.
https://github.com/sai3010/Typesense-Kubernetes-Operator#deploying-the-configuration

Closing this issue. Feel free to raise or reopen if needed.

**Comment by patrick-tavares** [comment]
I also experience this issue and used `kubectl create`:

```
[2023-12-19 15:26:15,720] kubernetes.client.re [DEBUG   ] response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"typesense\" already exists","reason":"AlreadyExists","details":{"name":"typesense","kind":"namespaces"},"code":409}

[2023-12-19 15:26:15,721] root                 [ERROR   ] Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"typesense\" already exists","reason":"AlreadyExists","details":{"name":"typesense","kind":"namespaces"},"code":409}
 
[2023-12-19 15:26:15,721] root                 [ERROR   ] Exception namespace: Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"typesense\" already exists","reason":"AlreadyExists","details":{"name":"typesense","kind":"namespaces"},"code":409}

[2023-12-19 15:26:15,722] kopf.objects         [ERROR   ] [typesense/typesense-operator] Handler 'create_fn' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/deployment_utils.py", line 53, in create_modify_namespace
    resp = core_obj.create_namespace(body=configuration)
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 6363, in create_namespace
    return self.create_namespace_with_http_info(body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 6454, in create_namespace_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 276, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 235, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'e86a27ad-356d-498a-96b6-c40edd0e2784', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'c15b04ad-9dc7-497c-991d-50353efea0cc', 'X-Kubernetes-Pf-Prioritylevel-Uid': '8e6b34a9-6601-438c-bc40-97edf64312bd', 'Date': 'Tue, 19 Dec 2023 15:26:15 GMT', 'Content-Length': '208'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"typesense\" already exists","reason":"AlreadyExists","details":{"name":"typesense","kind":"namespaces"},"code":409}



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/deployment_utils.py", line 57, in create_modify_namespace
    raise Exception(f"Kubernets Api Exception - Namespace: {e.body}")
Exception: Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"typesense\" already exists","reason":"AlreadyExists","details":{"name":"typesense","kind":"namespaces"},"code":409}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "handler.py", line 25, in create_fn
    create_modify_namespace(k8s_core_v1,namespace=spec['namespace'])
  File "/deployment_utils.py", line 60, in create_modify_namespace
    raise Exception(f"Exception namespace: {e}")
Exception: Exception namespace: Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"typesense\" already exists","reason":"AlreadyExists","details":{"name":"typesense","kind":"namespaces"},"code":409}

[2023-12-19 15:26:15,736] kopf.objects         [DEBUG   ] [typesense/typesense-operator] Patching with: {'metadata': {'annotations': {'kopf.zalando.org/create_fn': '{"started":"2023-12-19T15:26:15.694866","delayed":"2023-12-19T15:27:15.736114","purpose":"create","retries":1,"success":false,"failure":false,"message":"Exception namespace: Kubernets Api Exception - Namespace: {\\"kind\\":\\"Status\\",\\"apiVersion\\":\\"v1\\",\\"metadata\\":{},\\"status\\":\\"Failure\\",\\"message\\":\\"namespaces \\\\\\"typesense\\\\\\" already exists\\",\\"reason\\":\\"AlreadyExists\\",\\"details\\":{\\"name\\":\\"typesense\\",\\"kind\\":\\"namespaces\\"},\\"code\\":409}\\n"}'}}, 'status': {'kopf': {'progress': {'create_fn': {'started': '2023-12-19T15:26:15.694866', 'stopped': None, 'delayed': '2023-12-19T15:27:15.736114', 'purpose': 'create', 'retries': 1, 'success': False, 'failure': False, 'message': 'Exception namespace: Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \\"typesense\\" already exists","reason":"AlreadyExists","details":{"name":"typesense","kind":"namespaces"},"code":409}\n', 'subrefs': None}}}}}
[2023-12-19 15:26:15,816] kopf.objects         [WARNING ] [typesense/typesense-operator] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'create_fn': {'started': '2023-12-19T15:26:15.694866', 'stopped': None, 'delayed': '2023-12-19T15:27:15.736114', 'purpose': 'create', 'retries': 1, 'success': False, 'failure': False, 'message': 'Exception namespace: Kubernets Api Exception - Namespace: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \\"typesense\\" already exists","reason":"AlreadyExists","details":{"name":"typesense","kind":"namespaces"},"code":409}\n', 'subrefs': None}}}}, None),)
[2023-12-19 15:26:15,816] kopf.objects         [DEBUG   ] [typesense/typesense-operator] Sleeping was skipped because of the patch, 59.999605 seconds left.
[2023-12-19 15:26:15,920] kopf.objects         [DEBUG   ] [typesense/typesense-operator] Creation is in progress: {'apiVersion': 'typesenseproject.org/v1', 'config': {'password': 'hackathon'}, 'kind': 'TypesenseOperator', 'metadata': {'annotations': {'kopf.zalando.org/create_fn': '{"started":"2023-12-19T15:26:15.694866","delayed":"2023-12-19T15:27:15.736114","purpose":"create","retries":1,"success":false,"failure":false,"message":"Exception namespace: Kubernets Api Exception - Namespace: {\\"kind\\":\\"Status\\",\\"apiVersion\\":\\"v1\\",\\"metadata\\":{},\\"status\\":\\"Failure\\",\\"message\\":\\"namespaces \\\\\\"typesense\\\\\\" already exists\\",\\"reason\\":\\"AlreadyExists\\",\\"details\\":{\\"name\\":\\"typesense\\",\\"kind\\":\\"namespaces\\"},\\"code\\":409}\\n"}'}, 'creationTimestamp': '2023-12-19T15:26:15Z', 'finalizers': ['kopf.zalando.org/KopfFinalizerMarker'], 'generation': 1, 'managedFields': [{'apiVersion': 'typesenseproject.org/v1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kopf.zalando.org/create_fn': {}}, 'f:finalizers': {'.': {}, 'v:"kopf.zalando.org/KopfFinalizerMarker"': {}}}}, 'manager': 'kopf', 'operation': 'Update', 'time': '2023-12-19T15:26:15Z'}, {'apiVersion': 'typesenseproject.org/v1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:config': {'.': {}, 'f:password': {}}, 'f:spec': {'.': {}, 'f:image': {}, 'f:namespace': {}, 'f:nodeSelector': {'.': {}, 'f:kubernetes.io/os': {}}, 'f:replicas': {}, 'f:resources': {'.': {}, 'f:limits': {'.': {}, 'f:cpu': {}, 'f:memory': {}}, 'f:requests': {'.': {}, 'f:cpu': {}, 'f:memory': {}}}, 'f:storageClass': {'.': {}, 'f:name': {}, 'f:size': {}}}}, 'manager': 'kubectl-create', 'operation': 'Update', 'time': '2023-12-19T15:26:15Z'}], 'name': 'typesense-operator', 'namespace': 'typesense', 'resourceVersion': '26177923', 'uid': 'adb1d896-8c3e-4b5b-a930-b46b5aeeab82'}, 'spec': {'image': 'typesense/typesense:0.25.0', 'namespace': 'typesense', 'nodeSelector': {'kubernetes.io/os': 'linux'}, 'replicas': 1, 'resources': {'limits': {'cpu': '100m', 'memory': '200Mi'}, 'requests': {'cpu': '100m', 'memory': '100Mi'}}, 'storageClass': {'name': 'standard-rwo', 'size': '1Gi'}}}
[2023-12-19 15:26:15,921] kopf.objects         [DEBUG   ] [typesense/typesense-operator] Sleeping for 59.814539 seconds for the delayed handlers.
```

**Comment by mnlx** [comment]
Same issue as above. Why would using kubectl apply and create be any different. I have tried both, and still have this issue. I don't want it to create a namespace, this should be an optional config. For most users, we don't want operators creating namespaces.
